id: A47FCDB15
base_file: f0BAC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:54:28.653809
  last_modified_at: 2022-05-30 20:54:28.653827
